version: '3.7'
services:
  e_at_db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: e_at_db
    volumes:
      - ./mongodbdata:/data/db

  e_at_app:
    build:
      context: app
    ports:
      - 8080:8080

    depends_on:
      - e_at_db