version: '3.7'
services:
  e_at_db:
    image: mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  e_a_app:
    build:
      context: app
    ports:
      - 8080:5000

    depends_on:
      - e_at_db